import Link from "next/link";

export const metadata = {
  title: "Privacy Policy - Pulse 46",
  description: "Privacy Policy for Pulse 46 - Panic Attack Relief App",
};

export default function PrivacyPage() {
  return (
    <main className="gradient-bg min-h-screen">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 px-6 py-4 bg-[var(--bg-deep)]/80 backdrop-blur-lg">
        <div className="max-w-4xl mx-auto flex justify-between items-center">
          <Link href="/" className="flex items-center gap-2">
            <HeartIcon className="w-8 h-8 text-[var(--cyan-glow)]" />
            <span className="text-xl font-semibold">Pulse 46</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-[var(--cyan-glow)]">
              Privacy
            </Link>
            <Link href="/terms" className="text-[var(--text-secondary)] hover:text-[var(--cyan-glow)] transition-colors">
              Terms
            </Link>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="pt-32 pb-20 px-6">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-8">Privacy Policy</h1>
          <p className="text-[var(--text-secondary)] mb-12">Last updated: December 28, 2025</p>

          <div className="prose prose-invert max-w-none space-y-8">
            <Section title="Introduction">
              <p>
                Pulse 46 (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our mobile application.
              </p>
              <p>
                We built Pulse 46 with privacy as a core principle. The app is designed to work entirely on your device, with minimal data collection.
              </p>
            </Section>

            <Section title="Information We Collect">
              <h4 className="text-lg font-semibold text-[var(--cyan-glow)] mt-4 mb-2">Information You Provide</h4>
              <ul className="list-disc pl-6 space-y-2 text-[var(--text-secondary)]">
                <li><strong>Emergency Contacts:</strong> If you choose to add SOS contacts, this information is stored locally on your device only.</li>
                <li><strong>App Preferences:</strong> Your settings (sound preferences, haptic modes, etc.) are stored locally on your device using Apple&apos;s standard storage mechanisms.</li>
              </ul>

              <h4 className="text-lg font-semibold text-[var(--cyan-glow)] mt-6 mb-2">Information We Do NOT Collect</h4>
              <ul className="list-disc pl-6 space-y-2 text-[var(--text-secondary)]">
                <li>We do not collect personal identification information</li>
                <li>We do not track your location</li>
                <li>We do not access your contacts without explicit permission</li>
                <li>We do not collect health data</li>
                <li>We do not use analytics or tracking tools</li>
                <li>We do not share any data with third parties</li>
              </ul>
            </Section>

            <Section title="Data Storage">
              <p>
                All data generated by Pulse 46 is stored locally on your device. We do not have servers that store your personal information. Your preferences and any emergency contacts you add remain on your device and are not transmitted to us or any third party.
              </p>
            </Section>

            <Section title="Third-Party Services">
              <p>
                Pulse 46 uses RevenueCat for subscription management. RevenueCat may collect anonymous purchase data to process transactions. Please refer to <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[var(--cyan-glow)] hover:underline">RevenueCat&apos;s Privacy Policy</a> for more information.
              </p>
              <p>
                We do not use any advertising networks, analytics platforms, or other third-party services that track your behavior.
              </p>
            </Section>

            <Section title="Children's Privacy">
              <p>
                Pulse 46 does not knowingly collect personal information from children under 13. The app is designed for general audiences and does not require any personal information to function.
              </p>
            </Section>

            <Section title="Your Rights">
              <p>Since we don&apos;t collect personal data, there is no personal data for us to delete, modify, or export. All your data remains on your device and can be removed by uninstalling the app.</p>
            </Section>

            <Section title="Changes to This Policy">
              <p>
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date.
              </p>
            </Section>

            <Section title="Contact Us">
              <p>
                If you have any questions about this Privacy Policy, please contact us at:
              </p>
              <p className="mt-4">
                <a href="mailto:admin@pulse46.app" className="text-[var(--cyan-glow)] hover:underline">
                  admin@pulse46.app
                </a>
              </p>
            </Section>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-[rgba(255,255,255,0.05)]">
        <div className="max-w-4xl mx-auto text-center text-sm text-[var(--text-secondary)]">
          © {new Date().getFullYear()} Pulse 46. All rights reserved.
        </div>
      </footer>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">{title}</h2>
      <div className="text-[var(--text-secondary)] leading-relaxed space-y-4">
        {children}
      </div>
    </section>
  );
}

function HeartIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
    </svg>
  );
}



